### ISSUE TITLE
Encrypted Borpak idea

### ISSUE THREAD

**Issue by Lzetta** [rofl0r/openbor-legacy#1]
Could you create a secure(encrypted) borpak, to be used with the chronocrash openbor?

**Comment by rofl0r** [comment]
there is no such thing as a secure encrypted borpak. if the game (engine) is capable of unencrypting a pak, then the key must be stored somewhere. any sufficiently technical user will be able to find the key and extract the pak himself. you could only try "security-through-obscurity", e.g. hide the key in a binary build of the engine, but then again, people that know how to use a disassembler and a debugger, will be able to extract the key even from a binary.

**Comment by Lzetta** [comment]
The more technical users can make more quality games and have a fair use of the extracted content, but there some others new developers that make mods without quality and those have not much knowledge to extract things, they just copy paste and bad design. those are the ones i try to protect my content until at least finish my game.
Some developers from china uses a method that changes all extracted content from a pak file into a empty image or text file. (if extracted with default borpak)
Its not the most secure but is effective against the possible ones that could burn my game core with a bad design game.
but if you think it not worth i understand
